### ISSUE TITLE
3D CT Projection 

### ISSUE THREAD

**Issue by gmzang** [tancik/fourier-feature-networks#10]
Thanks for sharing this excellent code.
When running the 3d_MRI demo, I also found some functions for  3D CT data processing(such as get_shepp_dataset_3D) in it, I am wondering  is there also a CT Projection functions (similar to that in 2d_CT.ipynb) to run 3D CT reconstruction correctly?
In other words, do you have any demo for 3D_CT reconstruction? 
Thanks.

**Comment by pratulsrinivasan** [comment]
Thanks for your interest :-)
Unfortunately, we don't have any code for 3D CT experiments.
If you're interested in writing a forward model for 3D CT, I'd recommend starting with a function that follows the basic formula in the 2D CT experiments: generate indices for 3D samples --> rotate indices --> resample volume at these rotated indices --> integrate along one dimension
