### ISSUE TITLE
Where to download the 3D models?

### ISSUE THREAD

**Issue by Nuri-benbarka** [tancik/fourier-feature-networks#9]
Hi, 

I am trying to run the occupancy experiment, but I don't have the 3D models you used. Can you tell me where I can find them?

Thank you

**Comment by Timon-Hoefer** [comment]
Hi Nuri,

I was also looking for the object models. You can find them on this website:
[http://graphics.stanford.edu/data/3Dscanrep/](url)

Best regards
Timon

**Comment by Nuri-benbarka** [comment]
Thanks @Timon-Hoefer
